language: c

sudo: required

script:
  - make

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh aptget_install pandoc
  - ./travis-tool.sh aptget_install pandoc-citeproc
  - ./travis-tool.sh aptget_install texlive-latex-recommended
  - ./travis-tool.sh aptget_install texlive-xetex
  - ./travis-tool.sh aptget_install texlive-luatex
  - ./travis-tool.sh aptget_install pandoc-citeproc
  - ./travis-tool.sh aptget_install etoolbox
